'use client';
import React, { useEffect, useState } from 'react';
import { AlertTriangle, Check, ChevronRight, ClipboardCheck, FileText, Home, Mail, Menu, Plus, ShieldCheck, Truck, UserCog, Wrench, X } from 'lucide-react';

const stations = ['Station 30', 'Station 8', 'Station 14'];
const apparatus = [
  { id: 'T-30', station: 'Station 30', miles: '23494', hours: '2434' },
  { id: 'E-30', station: 'Station 30', miles: '18821', hours: '1986' },
  { id: 'BT-30', station: 'Station 30', miles: '12202', hours: '941' },
];
const sections = [
  { section: 'Starting Inspection', items: ['Starting inspection'] },
  { section: 'Outside Front, Rear & Undercarriage', items: ['Both front tires','Hub oil seal','Lug nuts','Rims','Lights','Door mirror & driver side door','Q siren','Front trash line','Windshield','Wiper blades','Axle seals','Bud wheels','Tires','Drums and linings','Steering box and hoses','Springs','Shock absorbers','Brake chamber','Brake hoses','Fuel tank'] },
  { section: 'Cab', items: ['Radio','Headsets','Seatbelts','Thermal camera','Map book','Fuel card'] },
];
const seedReports = [
  { ticket:'2C68AB30', type:'Daily Apparatus Check', unit:'T-30', date:'1/23/2026 08:24', status:'Issues', issues:['Lights: Pass side lower signal light out','Q siren','Wiper blades: Streaking','Horn: Inop'] },
  { ticket:'9FD21C77', type:'Apparatus Repair', unit:'E-30', date:'1/22/2026 15:12', status:'Open', issues:['Booster reel leak'] },
  { ticket:'5A90EF11', type:'Med Bag Check', unit:'Station 30', date:'1/21/2026 07:55', status:'Complete', issues:['No issues'] },
];
function cn(...c:any[]){return c.filter(Boolean).join(' ')}
function ticket(){return Math.random().toString(16).slice(2,10).toUpperCase()}

export default function App(){
 const [view,setView]=useState('dashboard'); const [station,setStation]=useState('Station 30'); const [reports,setReports]=useState<any[]>(seedReports);
 useEffect(()=>{const saved=localStorage.getItem('fireformsReports'); if(saved) setReports(JSON.parse(saved));},[]);
 useEffect(()=>{localStorage.setItem('fireformsReports',JSON.stringify(reports));},[reports]);
 async function addReport(r:any){ setReports(p=>[r,...p]); await fetch('/api/notify',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(r)}).catch(()=>null); setView('thanks'); }
 const last=reports[0];
 return <div className="min-h-screen bg-slate-100 text-slate-900"><Header view={view} setView={setView}/>{view==='dashboard'&&<Dashboard setView={setView} station={station} setStation={setStation}/>} {view==='daily'&&<Daily station={station} addReport={addReport}/>} {view==='repair'&&<Repair station={station} addReport={addReport}/>} {view==='med'&&<Med addReport={addReport}/>} {view==='stationRepair'&&<StationRepair addReport={addReport}/>} {view==='reports'&&<Reports reports={reports}/>} {view==='admin'&&<Admin/>} {view==='thanks'&&<Thanks last={last} setView={setView}/>} {view==='email'&&<Email report={last}/>}</div>
}
function Header({view,setView}:any){return <div className="sticky top-0 z-40 border-b bg-white/90 backdrop-blur"><div className="mx-auto flex max-w-6xl items-center justify-between px-4 py-3"><button onClick={()=>setView('dashboard')} className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-2xl bg-red-100 text-red-700"><ShieldCheck/></div><div className="text-left"><div className="text-xl font-black">FireForms</div><div className="text-xs font-medium text-slate-500">Deployable prototype</div></div></button><div className="hidden gap-2 md:flex">{[['dashboard','Home',Home],['reports','Reports',FileText],['admin','Admin',UserCog]].map(([k,l,I]:any)=><button key={k} onClick={()=>setView(k)} className={cn('flex items-center gap-2 rounded-xl px-3 py-2 text-sm font-semibold',view===k?'bg-slate-900 text-white':'text-slate-600 hover:bg-slate-100')}><I size={17}/>{l}</button>)}</div><Menu className="md:hidden"/></div></div>}
function Shell({children}:any){return <main className="mx-auto max-w-6xl px-4 py-6">{children}</main>}
function Dashboard({setView,station,setStation}:any){const forms=[['daily','Daily Apparatus Check','Walk-around and equipment checklist',ClipboardCheck],['repair','Apparatus Repair','Mechanical issue, service condition, photo',Wrench],['med','Med Bag Inventory','Bag contents and restock issues',Plus],['stationRepair','Station Repair Request','Building, bay, or facility issues',Home]]; return <Shell><div className="grid gap-6 lg:grid-cols-[1fr_360px]"><section><div className="mb-5 rounded-3xl bg-slate-900 p-6 text-white shadow-lg"><div className="mb-2 text-sm font-semibold text-slate-300">Facility</div><select value={station} onChange={e=>setStation(e.target.value)} className="w-full rounded-2xl bg-white px-4 py-3 text-lg font-bold text-slate-900">{stations.map(s=><option key={s}>{s}</option>)}</select><p className="mt-4 text-sm text-slate-300">Submissions create a ticket, save a report, and trigger email notification.</p></div><div className="grid gap-4 md:grid-cols-2">{forms.map(([id,title,desc,Icon]:any)=><button key={id} onClick={()=>setView(id)} className="group rounded-3xl border bg-white p-5 text-left shadow-sm hover:shadow-md"><div className="mb-5 flex items-center justify-between"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-red-50 text-red-700"><Icon size={26}/></div><ChevronRight className="text-slate-300 group-hover:text-slate-700"/></div><h3 className="text-lg font-black">{title}</h3><p className="mt-1 text-sm text-slate-500">{desc}</p></button>)}</div></section><aside className="rounded-3xl border bg-white p-5 shadow-sm"><h2 className="mb-4 font-black">Previous Issues</h2>{seedReports.map(r=><div key={r.ticket} className="mb-3 rounded-2xl bg-slate-50 p-4"><div className="font-black">{r.type}</div><div className="text-xs text-slate-500">{r.unit} • Ticket {r.ticket}</div><div className="mt-2 text-xs text-slate-600">{r.issues.join(', ')}</div></div>)}</aside></div></Shell>}
function Daily({station,addReport}:any){const unit=apparatus.find(a=>a.station===station)||apparatus[0]; const [app,setApp]=useState(unit.id); const [resp,setResp]=useState<any>(()=>Object.fromEntries(sections.flatMap(s=>s.items).map(i=>[i,{status:'pass',comment:''}]))); const cur=apparatus.find(a=>a.id===app); const issues=Object.entries(resp).filter(([,v]:any)=>v.status==='fail'); function status(item:string,s:string){setResp((p:any)=>({...p,[item]:{...p[item],status:s}}))} function comment(item:string,c:string){setResp((p:any)=>({...p,[item]:{...p[item],comment:c}}))} return <Shell><h1 className="text-2xl font-black">Daily Apparatus Check</h1><p className="mb-5 text-sm text-slate-500">Green means good. Red means somebody gets an email.</p><select value={app} onChange={e=>setApp(e.target.value)} className="input mb-4 max-w-xs">{apparatus.filter(a=>a.station===station).map(a=><option key={a.id}>{a.id}</option>)}</select><div className="mb-5 grid gap-3 md:grid-cols-3"><Info label="Asset" value={cur?.id}/><Info label="Miles" value={cur?.miles}/><Info label="Hours" value={cur?.hours}/></div>{sections.map(s=><div key={s.section} className="mb-5 rounded-3xl border bg-white p-4 shadow-sm"><h2 className="mb-3 font-black">{s.section}</h2>{s.items.map(item=>{const v=resp[item]; return <div key={item} className={cn('mb-3 rounded-2xl border p-3',v.status==='pass'?'border-green-200 bg-green-50':'border-red-200 bg-red-50')}><div className="flex flex-wrap items-center justify-between gap-3"><div className="font-bold">{item}</div><div className="flex gap-2"><button onClick={()=>status(item,'pass')} className={cn('rounded-xl px-3 py-2 text-sm font-black',v.status==='pass'?'bg-green-600 text-white':'bg-white text-slate-500')}><Check size={16} className="inline"/> Pass</button><button onClick={()=>status(item,'fail')} className={cn('rounded-xl px-3 py-2 text-sm font-black',v.status==='fail'?'bg-red-600 text-white':'bg-white text-slate-500')}><AlertTriangle size={16} className="inline"/> Issue</button></div></div>{v.status==='fail'&&<input value={v.comment} onChange={e=>comment(item,e.target.value)} placeholder="Comment / describe the issue" className="mt-3 w-full rounded-xl border bg-white px-3 py-2 text-sm"/>}</div>})}</div>)}<button onClick={()=>addReport({ticket:ticket(),type:'Daily Apparatus Check',unit:app,date:new Date().toLocaleString(),status:issues.length?'Issues':'Complete',issues:issues.length?issues.map(([i,v]:any)=>`${i}${v.comment?`: ${v.comment}`:''}`):['No issues']})} className="rounded-2xl bg-slate-900 px-6 py-3 font-black text-white">Submit Check</button></Shell>}
function Repair({station,addReport}:any){const [app,setApp]=useState('T-30'),[desc,setDesc]=useState(''),[cond,setCond]=useState('In service');return <Shell><div className="mx-auto max-w-3xl rounded-3xl border bg-white p-5 shadow-sm"><div className="mb-4 flex items-center gap-3"><Truck className="text-red-700"/><div><h1 className="text-2xl font-black">Apparatus Repair</h1><p className="text-sm text-slate-500">For anything permanently attached to the truck.</p></div></div><Field label="Apparatus"><select value={app} onChange={e=>setApp(e.target.value)} className="input">{apparatus.filter(a=>a.station===station).map(a=><option key={a.id}>{a.id}</option>)}</select></Field><Field label="Description"><textarea value={desc} onChange={e=>setDesc(e.target.value)} className="input min-h-32" placeholder="Describe the problem"/></Field><div className="mt-5 text-center text-lg font-black uppercase">Overall Service Condition</div><div className="mt-3 grid gap-3 md:grid-cols-3">{['In service','Out of service','Out of service due to this'].map(o=><button key={o} onClick={()=>setCond(o)} className={cn('rounded-2xl border p-5 font-black',cond===o?'bg-slate-900 text-white':'bg-slate-50 text-slate-500')}>{o}</button>)}</div><button onClick={()=>addReport({ticket:ticket(),type:'Apparatus Repair',unit:app,date:new Date().toLocaleString(),status:cond,issues:[desc||'No description entered']})} className="mt-6 w-full rounded-2xl bg-red-700 px-6 py-3 font-black text-white">Submit Repair Ticket</button></div></Shell>}
function Med({addReport}:any){const items=['Adult BVM','Pediatric BVM','OPA kit','NPA kit','Tourniquets','Trauma dressings','Glucometer','Narcan','Aspirin','Oxygen tubing']; const [missing,setMissing]=useState<string[]>([]); const toggle=(i:string)=>setMissing(p=>p.includes(i)?p.filter(x=>x!==i):[...p,i]); return <Shell><h1 className="text-2xl font-black">Med Bag Inventory</h1><p className="mb-5 text-sm text-slate-500">Tap missing or replacement items.</p><div className="grid gap-3 md:grid-cols-2">{items.map(i=><button key={i} onClick={()=>toggle(i)} className={cn('flex items-center justify-between rounded-2xl border p-4 font-bold',missing.includes(i)?'border-red-200 bg-red-50 text-red-800':'border-green-200 bg-green-50 text-green-800')}>{i}{missing.includes(i)?<X/>:<Check/>}</button>)}</div><button onClick={()=>addReport({ticket:ticket(),type:'Med Bag Check',unit:'Station 30',date:new Date().toLocaleString(),status:missing.length?'Restock Needed':'Complete',issues:missing.length?missing:['No issues']})} className="mt-6 rounded-2xl bg-slate-900 px-6 py-3 font-black text-white">Submit Med Bag Check</button></Shell>}
function StationRepair({addReport}:any){const [desc,setDesc]=useState(''); return <Shell><div className="mx-auto max-w-2xl rounded-3xl border bg-white p-5 shadow-sm"><h1 className="text-2xl font-black">Station Repair Request</h1><Field label="Problem"><textarea value={desc} onChange={e=>setDesc(e.target.value)} className="input min-h-32" placeholder="What needs fixing?"/></Field><button onClick={()=>addReport({ticket:ticket(),type:'Station Repair Request',unit:'Station 30',date:new Date().toLocaleString(),status:'Open',issues:[desc||'No description entered']})} className="mt-4 w-full rounded-2xl bg-slate-900 px-6 py-3 font-black text-white">Submit Request</button></div></Shell>}
function Reports({reports}:any){return <Shell><h1 className="mb-5 text-2xl font-black">Reports</h1>{reports.map((r:any)=><div key={r.ticket} className="mb-4 rounded-3xl border bg-white p-5 shadow-sm"><div className="mb-3 flex justify-between"><div><div className="text-lg font-black">{r.type}</div><div className="text-sm text-slate-500">{r.unit} • {r.date}</div></div><div className="font-mono text-lg font-black">{r.ticket}</div></div>{r.issues.map((i:string,idx:number)=><div key={idx} className={cn('mb-2 rounded-2xl p-3 font-bold',i==='No issues'?'bg-green-50 text-green-800':'bg-red-50 text-red-800')}>{i}</div>)}</div>)}</Shell>}
function Admin(){const [items,setItems]=useState(['Both front tires','Hub oil seal','Lug nuts','Rims','Lights','Q siren']); const [n,setN]=useState(''); return <Shell><h1 className="text-2xl font-black">Admin / Super User</h1><p className="mb-5 text-sm text-slate-500">Edit stations, apparatus, templates, recipients, and roles.</p><div className="rounded-3xl border bg-white p-5 shadow-sm"><h2 className="mb-4 font-black">T-30 Daily Check Template</h2>{items.map((i,idx)=><div key={i} className="mb-2 flex justify-between rounded-2xl bg-slate-50 p-3"><b>{idx+1}. {i}</b><button onClick={()=>setItems(items.filter(x=>x!==i))}><X className="text-red-700"/></button></div>)}<div className="mt-4 flex gap-2"><input value={n} onChange={e=>setN(e.target.value)} className="input" placeholder="Add checklist item"/><button onClick={()=>{if(n.trim()){setItems([...items,n.trim()]);setN('')}}} className="rounded-2xl bg-slate-900 px-4 font-black text-white">Add</button></div></div></Shell>}
function Thanks({last,setView}:any){return <Shell><div className="mx-auto max-w-xl rounded-3xl border bg-white p-8 text-center shadow-sm"><Check className="mx-auto mb-4 text-green-700" size={50}/><h1 className="text-2xl font-black">Thank you</h1><p className="mt-2 text-slate-600">Your information has been logged. Ticket <b className="font-mono">{last?.ticket}</b> was created.</p><div className="mt-6 flex justify-center gap-3"><button onClick={()=>setView('email')} className="rounded-2xl border px-5 py-3 font-black">Preview Email</button><button onClick={()=>setView('dashboard')} className="rounded-2xl bg-slate-900 px-5 py-3 font-black text-white">Return Home</button></div></div></Shell>}
function Email({report}:any){return <Shell><div className="mx-auto max-w-2xl rounded-3xl border bg-white p-6 shadow-sm"><div className="mb-4 flex gap-3"><Mail/><h1 className="text-xl font-black">Email Notification Preview</h1></div><div className="rounded-2xl bg-slate-900 p-4 text-white"><div className="text-sm text-slate-300">Subject</div><div className="font-black">{report.type} Completed ~ Ticket:{report.ticket}</div></div><p className="mt-5">A {report.type} has been submitted for {report.unit}.</p><b>Issues Identified:</b>{report.issues.map((i:string,idx:number)=><div key={idx} className="mt-2 rounded-xl bg-red-50 p-3 font-bold text-red-800">{i}</div>)}</div></Shell>}
function Info({label,value}:any){return <div className="rounded-2xl border bg-white p-4 shadow-sm"><div className="text-xs font-bold uppercase text-slate-400">{label}</div><div className="text-lg font-black">{value}</div></div>}
function Field({label,children}:any){return <label className="mt-4 block"><div className="mb-1 text-xs font-black uppercase text-slate-400">{label}</div>{children}</label>}
